#server:
#  port: 8082
#spring:
#  jpa:
#    database: POSTGRESQL
#    show-sql: true
#    hibernate:
#      ddl-auto: create
#  datasource:
#    platform: postgres
#    url: jdbc:postgresql://localhost:5432/checkout
#    username: postgres
#    password: Info@1234
#    driverClassName: org.postgresql.Driver
#
#
#    show-sql: true
#    hibernate:
#      ddlAuto: create-drop
#  application:
#    name: checkout
#  rabbitmq:
#    addresses: amqps://feibsqjg:On2bsDE32Ap27vHvIhqVRzOwW473dXLU@woodpecker.rmq.cloudamqp.com/feibsqjg
#
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
#  instance:
#    preferIpAddress: true

server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/checkout
    username: postgres
    password: Info@1234
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddlAuto: create-drop
  application:
    name: checkout
  rabbitmq:
    addresses: amqps://feibsqjg:On2bsDE32Ap27vHvIhqVRzOwW473dXLU@woodpecker.rmq.cloudamqp.com/feibsqjg

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true