#server:
#  port:8080
#
#spring:
#  jpa:
#    database: POSTGRESQL
#    show-sql: true
#    hibernate:
#      ddl-auto: create
#  datasource:
#    platform: postgres
#    url: jdbc:postgresql://localhost:5432/customer
#    username: postgres
#    password: Info@1234
#    driverClassName: org.postgresql.Driver
#
#  # /api-docs endpoint custom path
#  springdoc:
#    api-docs:
#      path: /api-docs
#    swagger-ui:
#      path: /swagger-ui.html
#
#  eureka:
#    client:
#      serviceUrl:
#        defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
#    instance:
#      preferIpAddress: true

server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/customer
    username: postgres
    password: Info@1234
    driverClassName: org.postgresql.Driver


  jpa:
    show-sql: true
    hibernate:
      ddlAuto: create-drop
  application:
    name: customer

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
